name: Docker

on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - mnival-patch-1
    paths-ignore:
      - '.github/workflows/**'
    
#  schedule:
#    - cron:  '15 00 * * *'

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        alpine-version: [edge, latest, 3.13]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ github.actor }}/alpine-postfix:${{ matrix.alpine-version }}
            ghcr.io/${{ github.actor }}/alpine-postfix:${{ matrix.alpine-version }}
          cache-from: |
            type=registry,ref=${{ github.actor }}/alpine-postfix:latest
            type=registry,ref=${{ github.actor }}/alpine-postfix:${{ matrix.alpine-version }}
          cache-to: type=inline
          build-args: |
            ALPINE_VERSION=${{ matrix.alpine-version }}
          labels: |
            org.opencontainers.image.revision=${{ github.sha }}
